# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mzml.io
email: muzamil@mzml.io
description: "Muzamil on the web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mzml.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title
author: Muzamil Satar
logo: /assets/
strict_front_matter: true

facebook:
  app_id:
  publisher:
  admins:

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:

social:
  links:
    twitter:  https://twitter.com/mzmls
    facebook: https://www.facebook.com/mzmls
    linkedin: https://www.linkedin.com/in/mzmls
    gplus:    https://plus.google.com/+MuzamilSatar
    github:   https://github.com/mzml

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-133301975-1