# site settings accessed via {{ site.title }}, {{ site.description }}, and so on.
title: mzml.io
description: "Muzamil on the web."
baseurl: ""
url: "https://www.mzml.io"
permalink: pretty
author: Muzamil
strict_front_matter: true

markdown: kramdown

sass:
  sass_dir: _scss
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons/"

google_analytics: UA-133301975-1