# site settings accessed via {{ site.title }}, {{ site.description }}, and so on.
title: mzml.io
description: "Muzamil on the web."
baseurl: ""
url: "https://www.mzml.io"
permalink: /:title
author: Muzamil Satar
strict_front_matter: true

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-133301975-1